### ISSUE TITLE
Search bar text on the front page is white on white background

### ISSUE THREAD

**Issue by maustin99** [seport/SLLA#21]
Bug: Search bar text on the front page is white on white background

<img width="1680" alt="screen shot 2018-02-07 at 8 00 20 pm" src="https://user-images.githubusercontent.com/23005268/35955011-c7a9dbbc-0c41-11e8-89b0-dda286c4dafe.png">

**Comment by seport** [comment]
Thanks for catching this! :)

**Comment by seport** [comment]
Resolved by #23
